### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by BUG423** [aau-cns/MSCEqF#2]
![image](https://github.com/aau-cns/MSCEqF/assets/73841802/f5ae5061-6a49-4739-8d37-0370a5338aee)

zhangshanshan@k8s-node5-ubuntu2004:~$ docker build --network=host -t msceqf:ros2 -f docker/Dockerfile_ros2
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

This will work：
docker build --network=host -t msceqf:ros2 -f docker/Dockerfile_ros2 .

**Comment by AlessandroFornasier** [comment]
Hi! As you just pointed out `docker build --network=host -t msceqf:ros2 -f docker/Dockerfile_ros2 .` should work.

**Comment by BUG423** [comment]
您好，我已经收到您的来信，非常感谢！祝好！
