### ISSUE TITLE
Encountering std::__ios_failure Error While Executing Test Code in Docker

### ISSUE THREAD

**Issue by BUG423** [aau-cns/MSCEqF#3]
![image](https://github.com/aau-cns/MSCEqF/assets/73841802/bc1b25b8-d8e4-45b2-80fe-f32baed6c661)

Content:
I encountered the following error message while attempting to execute test code within a Docker container:

terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_ios::clear: iostream error
Aborted (core dumped)

I am trying to run test code, but encountered a std::__ios_failure error during program execution. According to the error message, this is due to an iostream exception, but I am unsure of what caused this exception.

I have attempted to inspect possible errors in the code but have not found a solution. I am wondering if anyone has encountered a similar issue or has any suggestions on how to resolve this problem.

Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by BUG423** [comment]
The issue has been resolved. The solution was to create the folder for saving the results in advance. It's possible that the author accidentally deleted the folder when uploading the code.

**Comment by AlessandroFornasier** [comment]
Hi! Thanks for raising the issue. 

Yes, a `results` folder should be created prior to running the example.
