### ISSUE TITLE
error occurred when parse camera parameters

### ISSUE THREAD

**Issue by yueyunqingwu** [aau-cns/MSCEqF#6]
Hi Alessandro, thank you for your great work!
When parse camera parameters, an error occurs. The type of extrinsics_mat is Eigen::Matrix, while extrinsics is SE3, when extrinsics_mat assigns to extrinsics, raise an error, **terminate called after throwing an instance of 'std::invalid_argument' what():  SO3: QuaternionType has to be normalized!**, how can i fix it?
My extrinsic of camera is 
T_imu_cam:
  - [-0.06171486, 0.0726234, 0.99541608, 0.96885831]
  - [-0.99809154, -0.00647916, -0.06140622, -0.16231786]
  - [0.00199083, -0.99733858, 0.07288502, -0.47493288]
  - [0.0, 0.0, 0.0, 1.0]
Looking forward your replay.

**Comment by MarceloContreras** [comment]
I think the program is to sensitive to determinant != 1. I am having the same issue even after normalizing the rotation part with its determinant and increasing the number of digits to have better precision.

**Comment by AlessandroFornasier** [comment]
Hi! The latest commit on Lie++ is meant to solve this issue and normalize a given rotation that is not normalized. Please re-configure the project to pull the latest Lie++ and re-build.
